<?php

namespace CSCI242\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccountRepository extends EntityRepository
{
}
